### ISSUE TITLE
some questions of the result picture

### ISSUE THREAD

**Issue by lixiangMindSpore** [openai/glide-text2im#11]
![2](https://user-images.githubusercontent.com/78945582/147445954-13b3b694-c991-447f-8f0c-3882f26f0403.png)
prompt = "a woman"

What's wrong with this?

**Comment by lixiangMindSpore** [comment]
I use this
![image](https://user-images.githubusercontent.com/78945582/147446108-856ec1da-f67c-4c3f-a83f-63eb9f1d4117.png)

**Comment by woctezuma** [comment]
> prompt = "a woman"
> 
> What's wrong with this?

See #2. Click on the link to my repository, then read the model limitations in [the section called **Safety Considerations**](https://github.com/woctezuma/glide-text2im-colab#safety-considerations).

**Comment by unixpickle** [comment]
As pointed out by @woctezuma in the above link, the full model has not been released. The model in this repository was trained on a filtered dataset containing no images of people, and it is 10x smaller.
