### ISSUE TITLE
The result of generating people is incredible

### ISSUE THREAD

**Issue by cendelian** [openai/glide-text2im#16]
hi I try to use your great work to do some test.
but I found the result  is incredible when the prompt is about women and man.

for example, when the prompt is  "A woman with long hair and glasses "
result is 
![企业微信截图_16414535576761](https://user-images.githubusercontent.com/50360389/148344311-bdfdfb9f-3b31-4dc0-bc85-9cd8e48d7316.png)

I think  this model is unfriendly to generate people, isnt'it??

**Comment by woctezuma** [comment]
#11
