### ISSUE TITLE
disappointed, looks the model is poor for unseen data

### ISSUE THREAD

**Issue by world2vec** [openai/glide-text2im#35]
Hi,
I just have a try of text2im notebook in colab with simple text "a man fighting with 2 women", and it gives me

![text2img](https://user-images.githubusercontent.com/7607120/163525546-36167555-fdd9-4d64-a0a2-ff53d69012fa.png)

**Comment by woctezuma** [comment]
> with simple text "a man fighting with 2 women"

See #2. Click on the link to my repository, then read the model limitations in [the section called **Safety Considerations**](https://github.com/woctezuma/glide-text2im-colab#safety-considerations).

Related:
- #5 
- #11 
- #16
- #21 
- #26

**Comment by world2vec** [comment]
Thanks I can get the result with "a rooster  dance with 2 hens", not good but worked

![text2img](https://user-images.githubusercontent.com/7607120/163551822-889c3f21-a043-4d55-96d7-014e04830723.png)
