### ISSUE TITLE
How to get the results closer to what is shown in the paper?

### ISSUE THREAD

**Issue by kaloyan-chernev** [openai/glide-text2im#5]
Really inspirational work guys! 

But the results from the published code and models are not even remotely comparable to the shown results in the paper. Is there anything we can do to get closer to the original work?

- E.g. could we train on different (maybe bigger and more diverse) dataset? 
- Or do we need bigger model? 
- Or maybe tweaking the params a bit could help?

**Image from the paper for: "a surrealist dream-like oil painting by salvador dalı́ of a cat playing checkers"**

![image](https://user-images.githubusercontent.com/345458/147091706-1e1d04f4-f65b-4171-99c9-61a3f1953fca.png)

**Image from the code for the same text prompt "a surrealist dream-like oil painting by salvador..."**

![image](https://user-images.githubusercontent.com/345458/147091634-81ea4bbf-89ec-4c81-837f-d770e086d35c.png)

It's almost like that meme: " Your vs. The guy she told you not to worry about"  :rofl: 

Anyway, if you can give us some advice on this matter it would be greatly appreciated! :+1:

**Comment by woctezuma** [comment]
See https://github.com/openai/glide-text2im/issues/2#issuecomment-999037054.

**Comment by unixpickle** [comment]
We have not released the full GLIDE model--only GLIDE (filtered) which is 10x smaller than the original model and trained on a much more restricted dataset. We hope this model is still useful for future research, but it won't be able to reproduce the best images in the paper because of these limitations.
