### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by AminRezaei0x443** [openai/glide-text2im#7]
Really Great Work!
I wonder if you'll make training scripts available or not. If yes, are there any plans about when you'll make it available?
Thanks

**Comment by unixpickle** [comment]
We currently do not plan to make the training scripts available, although you can base training off of the implementation in [guided-diffusion](https://github.com/openai/guided-diffusion). The main part that is changed is data loading, which you will need to setup yourself with your own text-image dataset. We currently don't plan to release our dataset or data loader for this project.

**Comment by meatflavourdev** [comment]
That's fine and your right as the intellectual property creators, but if you're not going to be open, don't call yourselves "Open."

**Comment by rozeappletree** [comment]
> We currently do not plan to make the training scripts available, although you can base training off of the implementation in [guided-diffusion](https://github.com/openai/guided-diffusion). The main part that is changed is data loading, which you will need to setup yourself with your own text-image dataset. We currently don't plan to release our dataset or data loader for this project.

Hey @unixpickle,

Are the data loading strategies well defined in paper so that I might be able to reproduce it?

Best,
Rakesh

**Comment by alicedingyueming** [comment]
> We currently do not plan to make the training scripts available, although you can base training off of the implementation in [guided-diffusion](https://github.com/openai/guided-diffusion). The main part that is changed is data loading, which you will need to setup yourself with your own text-image dataset. We currently don't plan to release our dataset or data loader for this project.

May I ask for the training code for inpainting? Or can you provide me some hints for implementing a training script for inpainting?
